# Generated by Django 3.2.12 on 2022-04-03 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max length 250 symbols', max_length=250, verbose_name='Caption')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication`s date')),
                ('slug', models.SlugField(unique_for_date='pub_date', verbose_name='Slug')),
                ('main_page', models.BooleanField(default=False, help_text='Show', verbose_name='Main Page')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Max length 250 symbols', max_length=250, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category for new',
                'verbose_name_plural': 'Category for news',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Photo')),
                ('title', models.CharField(blank=True, help_text='Max 250 symbols', max_length=250, verbose_name='Caption')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_blog.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Photo for article',
                'verbose_name_plural': 'Photo for article',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_blog.category', verbose_name='Category'),
        ),
    ]
