# Generated by Django 3.2.12 on 2022-04-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category for publication', 'verbose_name_plural': 'Category for publications'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='def', verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app_blog.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_page',
            field=models.BooleanField(default=False, help_text='Show on main page', verbose_name='Main Page'),
        ),
    ]
